services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Repository implementation
    VendingMachine\VendingMachine\Infrastructure\Repository\DoctrineVendingMachineRepository:
        class: VendingMachine\VendingMachine\Infrastructure\Repository\DoctrineVendingMachineRepository
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Repository interface alias
    VendingMachine\VendingMachine\Domain\Port\VendingMachineRepositoryInterface:
        alias: VendingMachine\VendingMachine\Infrastructure\Repository\DoctrineVendingMachineRepository

    # Domain Services
    VendingMachine\VendingMachine\Domain\Service\ChangeCalculator:
        class: VendingMachine\VendingMachine\Domain\Service\ChangeCalculator

    VendingMachine\VendingMachine\Domain\Service\PurchaseProcessor:
        class: VendingMachine\VendingMachine\Domain\Service\PurchaseProcessor
        arguments:
            $changeCalculator: '@VendingMachine\VendingMachine\Domain\Service\ChangeCalculator'

    # Command Handlers - Customer
    VendingMachine\VendingMachine\Application\Customer\InsertCoin\InsertCoinCommandHandler:
        tags: ['messenger.message_handler']

    VendingMachine\VendingMachine\Application\Customer\Purchase\PurchaseProductCommandHandler:
        tags: ['messenger.message_handler']

    VendingMachine\VendingMachine\Application\Customer\ReturnCoin\ReturnCoinCommandHandler:
        tags: ['messenger.message_handler']

    # Command Handlers - Service
    VendingMachine\VendingMachine\Application\Service\Restock\RestockCommandHandler:
        tags: ['messenger.message_handler']

    # Query Handlers - Service
    VendingMachine\VendingMachine\Application\Service\GetInventory\GetInventoryQueryHandler:
        tags: ['messenger.message_handler']
