doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        # Register custom Doctrine types
        types:
            coin_array: VendingMachine\VendingMachine\Infrastructure\Doctrine\Type\CoinArrayType
            money: VendingMachine\VendingMachine\Infrastructure\Doctrine\Type\MoneyType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            VendingMachine:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VendingMachine/Domain'
                prefix: 'VendingMachine\VendingMachine\Domain'
                alias: VendingMachine
