# Entrypoint routes configuration
# HTTP Controllers routes

controllers:
    resource:
        path: ../../src/Entrypoint/Http/Controllers/
        namespace: VendingMachine\Entrypoint\Http\Controllers
    type: attribute